let alumnos = [["ANTONIO GONZALEZ LEHETH MADAI","8",0],
["ARZATE RUIZ MARCO JAZZEL","10",0],
["AYALA ARANDA ISRAEL","8",0],
["CID REYES GIOVANNA","10",0],
["DÍAZ MARGIL JOSE CARLOS","8",0],
["ESCOBAR GONZALEZ LUIS ALFREDO","8",0],
["ESPINOSA SILVA FRANZ IGNACIO","9",0],
["ESPINOZA RODRIGUEZ CRISTOPHER ALEXIS","10",0],
["FIGUEROA VALLE ADALID ANTUA","8",0],
["FLORES TELLEZ JAIR","8",0],
["GARCIA RODRIGUEZ CHRISTIAN EDUARDO","8",0],
["GERMAN HERNANDEZ CARLOS DAVID","8",0],
["GUADARRAMA MENDOZA RAÚL","7",0],
["HERRERA YAÑEZ SAMUEL OSWALDO","8",0],
["LEON CARVAJAL LUIS RAUL","9",0],
["LUCERO RAMIREZ RUBI","8",0],
["MENDEZ HERNANDEZ FRANCISCO","8",0],
["MIRANDA RENDON JEAN PIERRE HUMBERTO","8",0],
["MONTAÑO MORALES JOSE ALBERTO","12",0],
["MORALES MORALES BRYAN ALEJANDRO","8",0],
["NAVA FUENTES RAFAEL ANTONIO","10",0],
["PACHECO ALBERTO EMANUEL","8",0],
["PERALTA VARGAS RICARDO EMMANUEL","8",0],
["ROJAS JIMÉNEZ BETZAIDA AMARILIS","8",0],
["ROMERO GUTIERREZ JULIO CESAR","10",0],
["SAAVEDRA NIEVES DIEGO EDUARDO","8",0],
["SOTELO CHOPIN ULISES SHIE","8",0],
["TREJO NAVA ELIZABETH","10",0],
["VAZQUEZ VARGAS ERICK ALEJANDRO","8",0],
["ZAVALA LOPEZ ABRAHAM","10",0]];



function obtenerAlumno (id){
    return alumnos[id];
}

function setHorario (id){
    alumnos[id][2] = 1;
}
function dropHorario (id){
    alumnos[id][2] = 0;
}



/*module.exports = {
    "obtenerAlumno": obtenerAlumno,
}*/